### ISSUE TITLE
Provide an "Abstract Header Dropdown" component

### ISSUE THREAD

**Issue by askvortsov1** [flarum/issue-archive#202]
Flags currently inherits off of NotificationsDropdown for FlagsDropdown. This doesn't really make sense, aside from convenience reasons. We should provide an AbstractDropdown element from which both NotificationsDropdown, FlagsDropdown, and other dropdowns can inherit.

**Comment by franzliedke** [comment]
> Why? We'd need to move quite a lot of stuff into props, and I feel like that would overall be messier. Plus, this seems like a fairly standard is-a relation

👋🏼 Random answer and a greeting from the past:
When you have a "header dropdown" component and allow customization with slots (that's the key), then the possibilities of combining (i.e. re-using) things, mix and match them, are endless, compared to inheritance, which is always 1:1.
