### ISSUE TITLE
Suspended users shouldn't be allowed to change avatar

### ISSUE THREAD

**Issue by matteocontrini** [flarum/issue-archive#214]
Suspended users are currently allowed to change the avatar, potentially as a workaround for spreading spam or something else.

Suspended users shouldn't be allowed to do that.

**Comment by clarkwinkelmann** [comment]
This might be something to solve while we split the permissions for flarum/framework#1965

**Comment by askvortsov1** [comment]
> I would Like to work on this.

Great to hear! Would you also be interested in some aspects of the linked issue by any chance? Feel free to jump into that discussion 😁

**Comment by SychO9** [comment]
https://github.com/flarum/framework/pull/3890
