### ISSUE TITLE
Email unsubscribe links

### ISSUE THREAD

**Issue by franzliedke** [flarum/issue-archive#447]
See Google's mailing list guidelines:
https://support.google.com/mail/answer/81126?hl=en#unsub

> Because Gmail can help users automatically unsubscribe from your email, we strongly recommend the following:
> 
> Provide a 'List-Unsubscribe' header which points to an email address or a URL where the user can unsubscribe easily from future mailings. (Note: This is not a substitute method for unsubscribing.)

**Comment by neoncube2** [comment]
I'm also looking for this :)

As mentioned above, having an unsubscribe link at the bottom of an email is standard practice and is a legal requirement in some places. My understanding of the legal requirement is that the unsubscribe link:
* Only needs to unsubscribe the user from non-critical emails (e.g. it wouldn't apply to password reset emails, etc.)
* Should not require users to log in before unsubscribing. (e.g. It shouldn't just lead to the user's account settings page)

**Comment by neoncube2** [comment]
@askvortsov1 Can we expand this issue to include not only the `List-Unsubscribe` header but also the standard unsubscribe link?

It looks like https://github.com/flarum/framework/issues/1728 was closed as a duplicate of this, which I think is currently incorrect.

Thanks :)

**Comment by luceos** [comment]
This is already being worked on for 2.x.

**Comment by neoncube2** [comment]
@luceos The link and the header, or just the header?

**Comment by SychO9** [comment]
@neoncube2 both
